### ISSUE TITLE
Warning: undefined is not a function after upgrade to 3.2

### ISSUE THREAD

**Issue by robertlevy** [imagemin/imagemin#98]
So I realize this isn't a particularly helpful issue report because I don't have good repro steps to share but I wanted to let you know anyways...  Our CI builds started failing this morning (after 3.2 was released) with "Warning: undefined is not a function".  Removing all PNG files from the project made the build pass though that's not a real option.  We've reverted to 3.1 for the time being, adding an explicit dependency on that before our grunt-contrib-imagemin dependency.

**Comment by shinnn** [comment]
Could you show us the relevant part of the CI logs, more than just "Warning: undefined is not a function"?

**Comment by shinnn** [comment]
And, if you're using grunt-contrib-imagemin, you can see more helpful stack traces by adding [`--stack` flag](http://gruntjs.com/using-the-cli#stack) to the `grunt` command.

**Comment by kevva** [comment]
What version of `grunt-contrib-imagemin` are you using?

**Comment by robertlevy** [comment]
we're on 0.9.2 of grunt-contrib-imagemin.  will see if updating that solves the problem and try to share a stack trace if not

**Comment by robertlevy** [comment]
ok `grunt-contrib-imagemin 0.9.4` + `imagemin 3.2` === happiness.  thanks!

**Comment by kevva** [comment]
Sweet, happy it works.
