### ISSUE TITLE
Warning: Imagemin.pngquant is not a function after upgrade to 3.2

### ISSUE THREAD

**Issue by throrin19** [imagemin/imagemin#101]
Hello,
In Imagemin 3.1.0 i used `Imagemin.pngquant` to optimize my png images. After upgrade to 3.2, i have an error with this function and pngquant is not informed in the 3.2 documentation.
Why remove this function ? Normally, deprected functions are removed in major releases, not in minor releases.

**Comment by kevva** [comment]
Run `npm install imagemin-pngquant`.
