### ISSUE TITLE
TypeError: imagemin.svgo is not a function

### ISSUE THREAD

**Issue by alkorlos** [imagemin/imagemin#410]
Hello

Environment:
macOS Ventura 13.2
Use nvm, node.js 18.12.1
package.json "type": "module"

gulp-imagemin 7.1.0 works correctly
gulp-imagemin 8.0.0 not work

Code:
```js
return gulp.src('src/images/*')
		.pipe(imagemin([
			imagemin.svgo({
				plugins: [
					{removeViewBox: true},
					{cleanupIDs: false}
				]
			})
		]))
		.pipe(gulp.dest('dist/images'))
```

Error:
```sh
[09:35:01] 'svg' errored after 27 ms
[09:35:01] TypeError: imagemin.svgo is not a function
    at svg (file:///.../svg.js:17:13)
    at bound (node:domain:433:15)
    at runBound (node:domain:444:12)
    at asyncRunner (/Users/.../node_modules/async-done/index.js:55:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by Stephan-Pe** [comment]
Hi, here's a working example. Your setup should work on gulp-imagemin 7.1.0 the one below is on gulp-imagemin 8.0.0
https://github.com/Stephan-Pe/gulp_ECMA6
