### ISSUE TITLE
Fatal error: stream.on is not a function on windows 10, yeoman

### ISSUE THREAD

**Issue by horaciogiovine** [imagemin/imagemin#164]
Hi all, i downloaded a yeoman generator, im trying to use it for a project i want to do, the only error im getting is this:

```
Running tasks: imagemin

Loading "grunt-contrib-imagemin

Registering "C:\projects\admin-app\node_modules\grunt-contrib-imagemin\tasks" tasks.
Loading "imagemin.js" tasks...OK
+ imagemin
>> Plugin loaded.

Running "imagemin" task

Running "imagemin:dist" (imagemin) task
Verifying property imagemin.dist exists in config...OK
Files: client/assets/images/cash.jpg -> dist/public/assets/images/cash.jpg
Options: interlaced, optimizationLevel=3, progressive
Fatal error: stream.on is not a function Use --force to continue.

    Aborted due to warnings.
```

i have tried reinstalling everything, updating the package but no luck, does anyone know what this could be?
I also find no references to stream.on anywhere, any help is appreciated!

**Comment by shinnn** [comment]
No enough information.

**Comment by kevva** [comment]
This is most likely due to you using the wrong version of a custom plugin. We migrated away from streams to promises last week.

**Comment by patlux** [comment]
I'm using the latest version of `imagemin-pngquant` (5.0.0) and I get the same error on linux x64.

```
│TypeError: stream.on is not a function
│  at Readable.wrap (/project-folder/node_modules/readable-stre
│am/lib/_stream_readable.js:740:10)
│  at wrap (/project-folder/node_modules/stream-combiner2/index
│.js:67:29)
│  at combine (/project-folder/node_modules/stream-combiner2/in
│dex.js:29:18)
│  at Function.module.exports.obj (/project-folder/node_modules
│/stream-combiner2/index.js:22:10)
│  at Imagemin.createStream (/project-folder/node_modules/image
│min/index.js:103:24)
│  at Imagemin.run (/project-folder/node_modules/imagemin/index
│.js:77:20)
│  at DestroyableTransform.through.obj.percent (/project-folder
│/node_modules/gulp-imagemin/index.js:56:12)
│  at DestroyableTransform._transform (/project-folder/node_mod
│ules/through2-concurrent/through2-concurrent.js:29:15)
│  at DestroyableTransform.Transform._read (/project-folder/nod
│e_modules/readable-stream/lib/_stream_transform.js:159:10)
│  at DestroyableTransform.Transform._write (/project-folder/no
│de_modules/readable-stream/lib/_stream_transform.js:147:83)
│  at doWrite (/project-folder/node_modules/readable-stream/lib
│/_stream_writable.js:313:64)
│  at writeOrBuffer (/project-folder/node_modules/readable-stre
│am/lib/_stream_writable.js:302:5)
│  at DestroyableTransform.Writable.write (/project-folder/node
│_modules/readable-stream/lib/_stream_writable.js:241:11)
│  at DestroyableTransform.ondata (/project-folder/node_modules
│/readable-stream/lib/_stream_readable.js:531:20)
│  at emitOne (events.js:90:13)
│  at DestroyableTransform.emit (events.js:182:7)
│  at readableAddChunk (/project-folder/node_modules/readable-s
│tream/lib/_stream_readable.js:198:18)
│  at DestroyableTransform.Readable.push (/project-folder/node_
│modules/readable-stream/lib/_stream_readable.js:157:10)
│  at DestroyableTransform.Transform.push (/project-folder/node
│_modules/readable-stream/lib/_stream_transform.js:123:32)
│  at fsOperationFailed (/project-folder/node_modules/gulp-chan
│ged/index.js:17:10)
│  at /project-folder/node_modules/gulp-changed/index.js:30:8
│  at FSReqWrap.oncomplete (fs.js:82:15)
```

My gulp task:

```coffeescript
    gulp.src( config.images.src )
      .pipe( changed( config.images.dest ) )
      .pipe(
        imagemin(
          progressive:  true
          svgoPlugins:  [ removeViewBox: false ]
          use:          [ pngquant() ]
        )
        .on( 'error', handleError )
      )
      .pipe( gulp.dest( config.images.dest ) )

```

Its only working when I remove `pngquant()`.

**Comment by patlux** [comment]
ah okay, its working with 4.2.2 of `imagemin-pngquant`.

**Comment by antgonzales** [comment]
@kevva I'm getting the same errors:

`Fatal error: stream.on is not a function`

Here's what I have in my package.json:
```
"devDependencies": {
    "grunt": "~1.0.1",
    "grunt-browserify": "^4.0.1",
    "grunt-cli": "~1.2.0",
    "grunt-contrib-clean": "~1.0.0",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-imagemin": "~1.0.0",
    "grunt-contrib-jshint": "^1.0.0",
    "grunt-contrib-watch": "~1.0.0",
    "grunt-force-task": "^2.0.0",
    "grunt-sass": "^1.1.0",
    "grunt-svgmin": "~3.2.0",
    "grunt-svgstore": "latest",
    "imagemin-gifsicle": "^5.1.0",
    "imagemin-jpegoptim": "^5.0.0",
    "imagemin-mozjpeg": "^6.0.0",
    "imagemin-pngquant": "^5.0.0",
    "load-grunt-tasks": "~3.5.0"
  },
  "dependencies": {
    "angular": "^1.5.5",
    "angular-cookie": "^4.1.0",
    "angular-marked": "1.0.1",
    "angular-modal-service": "^0.6.10",
    "angular-route": "^1.5.5",
    "angular-slick-carousel": "^3.1.4",
    "angular-ui-mask": "latest",
    "bootstrap-sass": "^3.3.6",
    "breakpoint-sass": "^2.7.0",
    "font-awesome": "^4.6.1",
    "imagemin": "^4.0.0",
    "imagemin-jpegoptim": "^5.0.0",
    "imagemin-mozjpeg": "^6.0.0",
    "imagemin-pngquant": "^5.0.0",
    "jquery": "^2.2.3",
    "jquery-circle-progress": "^1.1.3",
    "underscore": "^1.8.3",
    "webcamjs": "^1.0.6"
  }
```
```node -v
v5.4.0```
Looks like everything is up to date, any other reason why `stream.on` would be a problem?

**Comment by kevva** [comment]
`imagemin` doesn't look to be up to date.

**Comment by arieluya** [comment]
I'm also having this issue -

  ```
"devDependencies": {
    "grunt": "~0.4.5",
    "grunt-contrib-concat": "^1.0.1",
    "grunt-contrib-cssmin": "^0.12.3",
    "grunt-contrib-imagemin": "^1.0.1",
    "grunt-contrib-jshint": "~0.10.0",
    "grunt-contrib-less": "*",
    "grunt-contrib-nodeunit": "~0.4.1",
    "grunt-contrib-uglify": "~0.5.0",
    "grunt-contrib-watch": "*",
    "grunt-image": "^2.1.0",
    "grunt-notify": "^0.4.5",
    "gulp": "^3.9.1",
    "gulp-imagemin": "^3.0.2",
    "imagemin-mozjpeg": "^5.1.0",
    "imagemin-pngquant": "^4.1.0"
  },
```
